spring.application.name=medgraph-backend
# Neo4j connection settings
spring.neo4j.uri=neo4j+s://2824ff75.databases.neo4j.io
spring.neo4j.authentication.username=2824ff75
spring.neo4j.authentication.password=eL7pSnPQHp7WhYNvq2zE1VgyoW3dl3FplIceQKo3wc0

# Optional: enable logging to see queries
logging.level.org.springframework.data.neo4j=DEBUG